spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dropboxdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: dropbox

file:
  upload-dir: /Users/rrauniyar/Documents/dropbox/src/main/resources/
