spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dropboxdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
   name: dropbox

file:
  upload-dir: /Users/rishav/Documents/dropbox/src/main/resources/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
